# Generated by Django 4.1.2 on 2023-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('dniclient', models.CharField(max_length=9)),
                ('fecnac', models.CharField(max_length=150)),
            ],
        ),
    ]
